### PR TITLE
Add CRP Projects (HZDR)

### PR DESCRIPTION
**Pull request by ax3l**
Adds projects from Michael @bussmann 's Computational Radiation Physics Group at HZDR.

### CODE REVIEW

**Comment by ax3l** [comment]
@bussmann list for the GCoE, just pushed together in 10min.
can you comment inline if you want something added/removed? thanks!

**Comment by tdd11235813** [comment]
cool, looks good. I gonna merge this. Let's see how this looks on the website...

**Comment by tdd11235813** [comment]
oh does not work lol
the underline "_" in issue tracker is missing, I'll fix that in a minute.
a tailored json tester would be helpful here^^

**Comment by tdd11235813** [comment]
k, spaces were not the problem ("issue tracker" is sanitized to "issue_tracker" by php).
it was just a superfluous comma at the end. [Now it is working](https://gcoe-dresden.de/?page_id=811).

**Comment by ax3l** [comment]
Cool, looks good!

**Pull request merged**
